# Generated by Django 6.0.6 on 2026-06-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('kidnapping', 'Kidnapping'), ('disparition', 'Disparition'), ('perte_objet', "Perte d'objet"), ('decouverte', 'Découverte'), ('accident', 'Accident')], max_length=50)),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('date_evenement', models.DateTimeField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('anonyme', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('cloture', 'Clôturé')], default='recu', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
