# Generated by Django 6.0.5 on 2026-05-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
