# Generated by Django 6.0.5 on 2026-06-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_envoi']},
        ),
    ]
