# Generated by Django 6.0.6 on 2026-06-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signalements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('valide', 'Validé'), ('rejete', 'Rejeté'), ('complement', 'Complément demandé')], max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('moderateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='signalements.signalement')),
            ],
            options={
                'ordering': ['-date_decision'],
            },
        ),
    ]
